'use client';

import React, { useState, useEffect } from 'react';
import { X, Download, Copy, Check, ShieldAlert, Shield, FileText, Sparkles } from 'lucide-react';
import { Recommendation } from '../types';

interface TenderClauseModalProps {
  recommendation: Recommendation;
  query: string;
  onClose: () => void;
}

export default function TenderClauseModal({ recommendation, query, onClose }: TenderClauseModalProps) {
  const [copied, setCopied] = useState(false);

  // Prevent body scroll when open
  useEffect(() => {
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, []);

  const generateClauseText = () => {
    const dateStr = new Date().toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const isMandatory = recommendation.metadata?.is_mandatory_qco;
    const references = recommendation.references || [];
    
    // Group references by relationship_type
    const groupedRefs = references.reduce((acc, ref) => {
      const type = ref.relationship_type || 'RELATED';
      if (!acc[type]) acc[type] = [];
      acc[type].push(ref);
      return acc;
    }, {} as Record<string, typeof references>);

    let referencesText = '';
    Object.entries(groupedRefs).forEach(([type, refs]) => {
      if (refs.length > 0) {
        referencesText += `\n   [${type}]:\n`;
        refs.forEach(ref => {
          referencesText += `   - ${ref.referenced_id}: ${ref.title || 'N/A'}\n`;
        });
      }
    });
    
    if (!referencesText) {
      referencesText = '\n   - No mandatory normative references found.\n';
    }

    const qcoText = isMandatory
      ? `   * MANDATORY COMPLIANCE under Section 16 of the BIS Act, 2016.
   * Manufacturer must hold a valid BIS License (ISI Mark / Scheme-I).
   * Bids offering uncertified or non-ISI marked items shall be summarily rejected.`
      : `   * No mandatory Quality Control Order (QCO) currently applies to this product category.
   * Bidders are encouraged to prefer BIS-certified products where available.`;

    return `TECHNICAL SPECIFICATION & COMPLIANCE CLAUSE
============================================
Tender Item: ${query}
Generated by: BIS Standards Recommendation Engine (PS 26108)
Date: ${dateStr}

1. PRIMARY APPLICABLE INDIAN STANDARD:
   The item shall strictly conform to ${recommendation.standard_id} (${recommendation.title}) - ${recommendation.metadata?.latest_version || 'Latest'}.

2. MANDATORY NORMATIVE & TESTING STANDARDS COMPLIANCE:
   All materials and verification tests must satisfy the cited normative references:${referencesText}
3. STATUTORY QUALITY CONTROL ORDER (QCO) COMPLIANCE:
${qcoText}

4. BIDDER SUBMISSION REQUIREMENTS:
   a. Valid copy of BIS Product Certification License with endorsement for offered sizes/ratings.
   b. Complete Type Test Report from NABL-accredited or BIS-approved laboratory.
   c. Written declaration of adherence to all normative and allied test standards.`;
  };

  const handleCopyClause = async () => {
    const text = generateClauseText();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handleDownloadTxt = () => {
    const text = generateClauseText();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `tender_clause_${recommendation.standard_id.replace(/[^a-zA-Z0-9_-]/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const isMandatory = recommendation.metadata?.is_mandatory_qco;
  const references = recommendation.references || [];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 md:p-10">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm" 
        onClick={onClose}
        aria-hidden="true"
      />
      
      {/* Modal Card - Spacious & Grand */}
      <div className="relative w-full max-w-4xl lg:max-w-5xl max-h-[90vh] bg-white rounded-2xl shadow-2xl flex flex-col overflow-hidden text-gray-900 border border-gray-200">
        
        {/* Header */}
        <div className="px-6 sm:px-8 py-5 border-b border-gray-100 flex items-start justify-between bg-white shrink-0">
          <div>
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-bis-saffron/15 text-amber-800 text-xs font-bold mb-2">
              <Sparkles className="w-3.5 h-3.5 text-bis-saffron" />
              <span>✦ GEM READY CLAUSE</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-bis-blue tracking-tight">
              Tender Specification & Compliance Clause Generator
            </h2>
            <p className="text-xs sm:text-sm text-gray-500 mt-1">
              Official technical procurement annexure drafted for <span className="font-semibold text-bis-blue">{recommendation.standard_id}</span>
            </p>
          </div>
          <button 
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full transition-colors cursor-pointer"
            aria-label="Close"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="px-6 sm:px-8 py-6 overflow-y-auto flex-1 space-y-6 text-sm leading-relaxed">
          
          {/* Section 1 */}
          <div className="pl-4 border-l-4 border-bis-blue">
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1.5">
              1. Primary Applicable Indian Standard
            </h3>
            <p className="text-gray-900 font-medium text-base">
              The item shall strictly conform to <span className="font-bold text-bis-blue">{recommendation.standard_id}</span> ({recommendation.title}) — {recommendation.metadata?.latest_version || 'Latest Revision'}.
            </p>
          </div>

          {/* Section 2 */}
          <div className="pl-4 border-l-4 border-bis-blue">
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">
              2. Mandatory Normative & Testing Standards Compliance
            </h3>
            {references.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {references.map((ref, idx) => (
                  <div key={idx} className="bg-gray-50/90 p-3.5 rounded-xl border border-gray-100 flex items-start justify-between gap-3 hover:border-gray-200 transition-colors">
                    <div className="flex-1 min-w-0">
                      <div className="font-bold text-bis-blue text-sm">{ref.referenced_id}</div>
                      <div className="text-gray-600 text-xs mt-0.5 line-clamp-2">{ref.title || 'N/A'}</div>
                    </div>
                    <span className="text-[10px] font-mono tracking-wider font-semibold px-2.5 py-1 rounded-full uppercase bg-blue-100 text-blue-800 border border-blue-200 shrink-0">
                      {(ref.relationship_type || 'RELATED').replace(/_/g, ' ')}
                    </span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-gray-500 italic text-xs">No normative cross-references cited.</p>
            )}
          </div>

          {/* Section 3 */}
          <div className="pl-4 border-l-4 border-bis-blue">
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">
              3. Statutory Quality Control Order (QCO) Declaration
            </h3>
            {isMandatory ? (
              <div className="bg-red-50 border border-red-200/80 rounded-xl p-4 text-red-900 space-y-2">
                <div className="flex items-center gap-2 font-bold text-red-800 text-sm sm:text-base">
                  <ShieldAlert className="w-5 h-5 shrink-0" />
                  <span>MANDATORY COMPLIANCE under Section 16 of the BIS Act, 2016</span>
                </div>
                <ul className="list-disc pl-5 space-y-1 text-xs sm:text-sm text-red-800">
                  <li>Manufacturer must hold a valid BIS Product Certification License (ISI Mark / Scheme-I).</li>
                  <li>Bids offering uncertified or non-ISI marked items shall be summarily rejected at technical evaluation.</li>
                </ul>
              </div>
            ) : (
              <div className="bg-green-50 border border-green-200/80 rounded-xl p-4 text-green-900 space-y-1.5">
                <div className="flex items-center gap-2 font-semibold text-green-800 text-sm sm:text-base">
                  <Shield className="w-5 h-5 shrink-0" />
                  <span>Voluntary Standard Category</span>
                </div>
                <p className="text-xs sm:text-sm text-green-800">
                  No mandatory Quality Control Order (QCO) currently applies; BIS-certified goods are preferred in technical scoring.
                </p>
              </div>
            )}
          </div>

          {/* Section 4 */}
          <div className="pl-4 border-l-4 border-bis-blue">
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">
              4. Bidder Submission Requirements
            </h3>
            <ul className="list-disc pl-5 space-y-1.5 text-xs sm:text-sm text-gray-700 bg-gray-50/80 p-4 rounded-xl border border-gray-100">
              <li>Valid copy of BIS Product Certification License with endorsement for offered sizes/ratings.</li>
              <li>Complete Type Test Report from NABL-accredited or BIS-approved laboratory.</li>
              <li>Written declaration of adherence to all normative and allied test standards.</li>
            </ul>
          </div>

        </div>

        {/* Footer with Spacious Layout */}
        <div className="px-6 sm:px-8 py-4 bg-gray-50 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-4 shrink-0">
          <div className="flex items-center gap-2 text-xs sm:text-sm text-gray-500 min-w-0 flex-1">
            <FileText className="w-4 h-4 text-gray-400 shrink-0" />
            <span>Format strictly conforms to GeM Section IV Technical Specifications Annexure</span>
          </div>
          <div className="flex items-center gap-3 shrink-0">
            <button
              onClick={handleDownloadTxt}
              className="flex items-center justify-center gap-2 px-5 py-2.5 border border-gray-300 bg-white text-gray-700 text-xs sm:text-sm font-semibold rounded-lg hover:bg-gray-50 hover:text-gray-900 transition-colors cursor-pointer shadow-sm whitespace-nowrap"
            >
              <Download className="w-4 h-4" />
              <span>Download .txt</span>
            </button>
            <button
              onClick={handleCopyClause}
              className="flex items-center justify-center gap-2 px-6 py-2.5 bg-bis-blue hover:bg-blue-900 text-white text-xs sm:text-sm font-semibold rounded-lg transition-colors cursor-pointer shadow-sm active:scale-[0.98] whitespace-nowrap"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied!' : 'Copy Tender Clause'}</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
